# Generated by Django 3.0.3 on 2020-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_study_app1', '0005_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_sample.png', null=True, upload_to=''),
        ),
    ]
