# Generated by Django 3.0.3 on 2020-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_study_app1', '0008_auto_20200715_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_sample_U9qz6vF.png', null=True, upload_to=''),
        ),
    ]
